version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
      
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: challenge-java-v2
    container_name: challenge-java-v2
    logging:
      driver: "json-file"
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis
      - MONGODB_URI=mongodb://mongo:27017/SalePointCredentialDB
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - redis
      - mongo
    networks:
      - app-network
      
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: app-tests
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge