version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  app:
    image: challenge-java-v2
    container_name: challenge-java-v2
    logging:
      driver: "json-file"
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - SPRING_CACHE_TYPE=${SPRING_CACHE_TYPE}
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge