apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-java-v2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-java-v2
  template:
    metadata:
      labels:
        app: challenge-java-v2
    spec:
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
      containers:
        - name: app
          image: challenge-java-v2:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 2911
              hostPort: 2911
              protocol: TCP
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          env:
            - name: SPRING_REDIS_HOST
              value: redis-service
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_CACHE_TYPE
              value: "redis"
            - name: SERVER_PORT
              value: "2911"
            - name: KEYSTORE_PATH
              value: "classpath:keystore.p12"
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: challenge-java-v2-secrets
                  key: keystore_password
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: challenge-java-v2-secrets
                  key: mongo_connection_string
        - name: log-forwarder
          image: fluent/fluent-bit:latest
          securityContext:
            privileged: true
            runAsUser: 0
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: challenge-java-v2
  ports:
    - protocol: TCP
      port: 2911
      targetPort: 2911
  type: ClusterIP