apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        flush        1
        daemon       off
        log_level    info
        parsers_file parsers.conf

    [INPUT]
        Name tail
        Path /var/log/app/application.log
        Tag challenge-java-v2
        Read_from_Head On

    [OUTPUT]
        Name loki
        Match *
        Host loki.default.svc.cluster.local
        Port 3100
        URI /loki/api/v1/push
        Labels job=challenge-java-v2,container=app

  parsers.conf: |
    [PARSER]
        Name json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%fZ